name: Build and Test
run-name: ${{ github.actor }} tests https://www.globalsqa.com/angularJs-protractor/BankingProject/#/manager

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean install
      - name: Run tests
        run: mvn test